[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "calra"
authors = [{name = "Daeng Deni Mardaeni", email = "daeng.deni@iat.id"}]
dynamic = ["version", "description"]
